baseurl = "https://embeddedk8.com/"
title = "Embedded Kate"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

[services]
#[services.disqus]
#shortname = "yourdiscussshortname"

[markup.highlight]
style = "github-light"

[params]
author = "Kate"
info = ["Low level engineer"]
description = "I share my thoughts and in-depth articles on embedded systems, RTOS, and C programming"
keywords = "embedded,rtos,blog"
avatarurl = "images/avatar.png"
#gravatar = "john.doe@example.com"
faviconSVG = "/img/favicon.svg"
favicon_32 = "/img/favicon-32x32.png"
favicon_16 = "/img/favicon-16x16.png"

since = 2025

enableTwemoji = true

colorScheme = "auto"
hidecolorschemetoggle = false

# customCSS = ["css/custom.css"]
# customSCSS = ["scss/custom.scss"]
# customJS = ["js/custom.js"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/embeddedk8/"
[[params.social]]
name = "Twitter"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 3
url = "https://x.com/EmbeddedKate/"

[params.giscus]
# You can refer to the official documentation of giscus to use the following configuration.
enable = true
repo = "embeddedk8/embeddedk8.github.io"
repoId = "R_kgDOPvP-ig"
category = "Announcements"
categoryId = "DIC_kwDOPvP-is4CwE3r"
# automatically adapt the current theme i18n configuration when empty
lang = ""
mapping = "pathname"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom"
lazyLoading = false
lightTheme = "light"
darkTheme = "dark"


# Menu links
[[menu.main]]
name = "Blog"
weight = 1
url  = "posts/"
[[menu.main]]
name = "Categories"
weight = 1
url  = "categories/"
[[menu.main]]
name = "About"
weight = 2
url = "about/"